=== tfreese/misc/de.freese.sonstiges/src/main/resources/navigationTree.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.example.org/NavigationSchema" targetNamespace="http://www.example.org/NavigationSchema"
	elementFormDefault="qualified">

	<xs:complexType name="nodeType">
		<xs:sequence>
			<xs:element name="context" type="xs:string" />
			<xs:element name="modul" type="xs:string" />
			<xs:element name="class" type="xs:string" />
			<xs:element name="icon" type="xs:string" />
			<xs:element name="node" type="nodeType" minOccurs="0"
				maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="treeType">
		<xs:sequence>
			<xs:element name="node" type="nodeType" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="navigationTree" type="treeType" />
</xs:schema>

=== tfreese/misc/sonstiges/src/main/resources/navigationTree.xml
<?xml version="1.0" encoding="UTF-8"?>

<navigationTree xmlns="http://www.example.org/NavigationSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pim="http://www.example.org/PIMSchema"
	xsi:schemaLocation="
		http://www.example.org/NavigationSchema navigationTree.xsd
		http://www.example.org/PIMSchema pim.xsd ">

	<node>
		<context>Context 1</context>
		<modul>Modul 1</modul>
		<class>Class 1</class>
		<icon>Icon 1</icon>
	</node>
	<node>
		<context>Context 2</context>
		<modul>Modul 2</modul>
		<class>Class 2</class>
		<icon>Icon 2</icon>

		<node>
			<context>Context 3</context>
			<modul>Modul 3</modul>
			<class>Class 3</class>
			<icon>Icon 3</icon>
		</node>
	</node>

</navigationTree>
